import { Enum } from "cc";

const GameEvent = Enum({
	NONE: 0,
	RESIZE: 10,
	REDIRECT: 20,
	INPUT: 30,
	SET_AUDIO_VOLUME: 40,
	FIRST_TAP: 60,
	TOGGLE_HIDABLE: 70,
	JOYSTICK_DOWN: 80,
	JOYSTICK_MOVE: 90,
	JOYSTICK_UP: 100,
	MOVE_DIRECTION: 110,
	DOOR_OPEN: 120,
	DOOR_CLOSE: 130,
	GAME_COMPLETE: 140,
});

export default GameEvent;
